import Navbar from "@components/Navbar";
import Footer from "@components/Footer";
import "./globals.css";

export const metadata = {
  title: "Smart Tour Dynamic",
  description: "Generated by Medusa Global",
};



export default function RootLayout({ children}) {

  return (
    <html>
      <body className="flex flex-col justify-start items-center">
        <Navbar />
        <main className="flex flex-col items-center justify-start">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
